-- Core table for the URL shortener baseline: short code -> destination URL,
-- with expiration support and a soft-disable flag.
-- Analytics tables are intentionally not created here.

CREATE TABLE short_urls (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code    VARCHAR(16)  NOT NULL,
    original_url  VARCHAR(2048) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_short_urls_short_code UNIQUE (short_code)
);

-- Supports the "list/purge expired" style lookups without scanning the table.
CREATE INDEX idx_short_urls_expires_at ON short_urls (expires_at);
