-- Greenfield increment: click analytics for shortened URLs.
--
-- One row per successful redirect of an active, non-expired short URL. Nothing is
-- recorded for unknown, disabled or expired codes.
--
-- Privacy by design: only the moment of the click and the (optional) referrer are
-- stored. No IP address, no user agent, no geo-location, no device fingerprint -
-- none of that is needed for the click counts this feature exposes.

CREATE TABLE click_events (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id BIGINT       NOT NULL REFERENCES short_urls (id),
    clicked_at   TIMESTAMPTZ  NOT NULL,
    referrer     VARCHAR(512)
);

-- Serves both "total clicks" and "most recent clicks" for a short URL.
CREATE INDEX idx_click_events_short_url ON click_events (short_url_id, clicked_at DESC);
