-- Core orchestration schema: requirement -> workflow run -> versioned task graph,
-- plus agent executions, decision lineage and the audit trail.
-- Governance (approvals), recovery (retry/rollback) and metrics tables are added
-- by later migrations together with the features that need them.

CREATE TABLE requirements (
    id          UUID        PRIMARY KEY,
    text        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE workflow_runs (
    id                    UUID        PRIMARY KEY,
    requirement_id        UUID        NOT NULL REFERENCES requirements (id),
    status                VARCHAR(32) NOT NULL,
    current_graph_version INTEGER     NOT NULL,
    error_message         TEXT,
    created_at            TIMESTAMPTZ NOT NULL,
    started_at            TIMESTAMPTZ,
    completed_at          TIMESTAMPTZ,
    version               BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX idx_workflow_runs_status ON workflow_runs (status);

CREATE TABLE workflow_graph_versions (
    id              UUID        PRIMARY KEY,
    workflow_run_id UUID        NOT NULL REFERENCES workflow_runs (id),
    version         INTEGER     NOT NULL,
    description     VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_graph_version UNIQUE (workflow_run_id, version)
);

CREATE TABLE workflow_tasks (
    id               UUID        PRIMARY KEY,
    workflow_run_id  UUID        NOT NULL REFERENCES workflow_runs (id),
    graph_version_id UUID        NOT NULL REFERENCES workflow_graph_versions (id),
    task_key         VARCHAR(64) NOT NULL,
    name             VARCHAR(128) NOT NULL,
    agent_type       VARCHAR(48) NOT NULL,
    status           VARCHAR(32) NOT NULL,
    sequence_no      INTEGER     NOT NULL,
    input_context    TEXT,
    output_context   TEXT,
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    version          BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_task_key_per_graph UNIQUE (graph_version_id, task_key)
);

CREATE INDEX idx_workflow_tasks_run_status ON workflow_tasks (workflow_run_id, status);

CREATE TABLE task_dependencies (
    id                 UUID PRIMARY KEY,
    task_id            UUID NOT NULL REFERENCES workflow_tasks (id),
    depends_on_task_id UUID NOT NULL REFERENCES workflow_tasks (id),
    CONSTRAINT uk_task_dependency UNIQUE (task_id, depends_on_task_id),
    CONSTRAINT ck_task_dependency_not_self CHECK (task_id <> depends_on_task_id)
);

CREATE INDEX idx_task_dependencies_task ON task_dependencies (task_id);

CREATE TABLE agent_executions (
    id              UUID        PRIMARY KEY,
    workflow_run_id UUID        NOT NULL REFERENCES workflow_runs (id),
    task_id         UUID        NOT NULL REFERENCES workflow_tasks (id),
    agent_type      VARCHAR(48) NOT NULL,
    status          VARCHAR(32) NOT NULL,
    input_context   TEXT,
    output          TEXT,
    error_message   TEXT,
    started_at      TIMESTAMPTZ NOT NULL,
    completed_at    TIMESTAMPTZ
);

CREATE INDEX idx_agent_executions_task ON agent_executions (task_id);

CREATE TABLE decisions (
    id              UUID         PRIMARY KEY,
    workflow_run_id UUID         NOT NULL REFERENCES workflow_runs (id),
    task_id         UUID         REFERENCES workflow_tasks (id),
    decision_type   VARCHAR(64)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    rationale       TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_decisions_run ON decisions (workflow_run_id);

CREATE TABLE audit_events (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_run_id UUID        NOT NULL REFERENCES workflow_runs (id),
    task_id         UUID        REFERENCES workflow_tasks (id),
    event_type      VARCHAR(48) NOT NULL,
    message         VARCHAR(512) NOT NULL,
    details         TEXT,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_audit_events_run ON audit_events (workflow_run_id, id);
